name: CI-CD

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: andreslon/eafit-react-app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:${{ github.sha }}

    - name: Push the Docker image
      run: docker push $DOCKER_IMAGE_NAME:${{ github.sha }}